# Generated by Django 3.1.5 on 2021-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210112_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
