# Generated by Django 3.1.5 on 2021-01-23 03:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20210114_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_watchlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('indiv_watchlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_watch_list_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_watch_list_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
