# Generated by Django 3.1.5 on 2021-01-23 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_movielike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielike',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
