# Generated by Django 3.1.5 on 2021-01-24 04:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210123_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='indiv_watchlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='shared_watchlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
