# Generated by Django 3.1.5 on 2022-01-01 23:28

from django.db import migrations, models
import profiles.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.TextField(blank=True, default=profiles.models.user.avatar_color_default),
        ),
    ]
