# Generated by Django 3.1.5 on 2022-01-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_avatar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='active',
        ),
    ]
