# Generated by Django 3.1.5 on 2021-01-14 16:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20210112_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_list_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
