# Generated by Django 3.1.5 on 2022-01-22 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220120_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchlistdislike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='matchlistlike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='watchlistmovie',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
