# Generated by Django 3.1.5 on 2021-01-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_jointwatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointwatchlist',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_watch_list_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jointwatchlist',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_watch_list_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
