# Generated by Django 3.1.5 on 2021-01-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210124_0417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JointWatchlist',
        ),
    ]
